### ISSUE TITLE
Help Wanted – Athena Troubleshooting, Tips, and Tricks

### ISSUE THREAD

**Issue by JuliaMalkin** [awsdocs/amazon-athena-user-guide#14]
Please share your experience! If you've hit a problem and solved it, I’d love to hear from you. I am also interested in any tips or tricks you’ve learned along the way.

Submit a pull request (instructions here) or send me a note via the Comments below. If your suggestion is likely to help others, I'll add it to the [Athena User Guide](https://docs.aws.amazon.com/athena/latest/ug/what-is.html).

Thank you for your time. I look forward to hearing from you!

**Comment by SqlAdmin** [comment]
I was running into an issue to automate the partition creation on daily basis for query the CloudTrail logs. The solution should not be in a single point of failure. So I have automated this with Lambda. We can use the same solution for creating partitions for Load balancer logs. 

**Here is the code for this:**
[https://gist.github.com/SqlAdmin/4e2500bf358dd611ad2da97a1e641a65](url)
**A blog:** [https://medium.com/searce/https-medium-com-searce-automate-aws-athena-partitions-for-cloudtrail-logs-on-daily-basis-924f68fbb74b](url)

Also another problem with this CloudTrail and ELB logs is how to create partitions for existing date range.
Here is the solution I have implemented for this. It'll work on Lambda and python on EC2.
**Code**: [https://gist.github.com/SqlAdmin/d55938f7ff8202508618c3f8dfe5883e](url)
**Blog URL:** [https://www.sqlgossip.com/automatically-create-aws-athena-partitions-for-cloudtrail-between-two-dates/](url)

**Comment by JuliaMalkin** [comment]
Thank you for your suggestions and links. Can you please check the links as they won't open.

**Comment by SqlAdmin** [comment]
Links are fixed!

**Comment by 0xdabbad00** [comment]
This is not Athena specific, but a common use case of Athena mentioned by AWS is for querying CloudTrail logs.  The CloudTrail service writes objects to S3 with object ACLs.  The result of this is that if you have Account A logging to an S3 bucket in Account A, and then you try to have Account B querying these logs, it will not work. You might expect you can set a bucket policy to allow Account B to read these logs, but due to the object ACLs, this is not possible. You have to copy these files, or otherwise remove the ACLs, in order to access the objects with Athena or anything else from Account B, or you have to have Account A send CloudTrail logs to an S3 bucket in Account B.

**Comment by SqlAdmin** [comment]
0xdabbad00, Yes, you are correct, but I prepared this lambda for that particular account.  It'll create the partitions. It won't create partitions on another account. But we can assign policies to run this query on Another account.  But the intention here is to automate the create partition part (for lazy peoples like me :)  )
